In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

                    GET DUMMIES IS UISED TO CONVERT CATEGORIAL DATA INTO CONTINUES

In [3]:
df =  pd.get_dummies(df, drop_first = True)   #### it took gender
df

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
x = df.iloc[:,[1,2,4]].values
y = df.iloc[:,-2].values

In [5]:
x

array([[   19, 19000,     1],
       [   35, 20000,     1],
       [   26, 43000,     0],
       ...,
       [   50, 20000,     0],
       [   36, 33000,     1],
       [   49, 36000,     0]], dtype=int64)

                    SPLITTING DATA INTO TRAIN_TEST

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [7]:
x_train

array([[    44,  39000,      0],
       [    32, 120000,      1],
       [    38,  50000,      0],
       [    32, 135000,      0],
       [    52,  21000,      0],
       [    53, 104000,      0],
       [    39,  42000,      1],
       [    38,  61000,      1],
       [    36,  50000,      0],
       [    36,  63000,      0],
       [    35,  25000,      0],
       [    35,  50000,      1],
       [    42,  73000,      1],
       [    47,  49000,      0],
       [    59,  29000,      0],
       [    49,  65000,      1],
       [    45, 131000,      0],
       [    31,  89000,      0],
       [    46,  82000,      0],
       [    47,  51000,      0],
       [    26,  15000,      1],
       [    60, 102000,      1],
       [    38, 112000,      0],
       [    40, 107000,      1],
       [    42,  53000,      0],
       [    35,  59000,      1],
       [    48,  41000,      1],
       [    48, 134000,      0],
       [    38, 113000,      0],
       [    29, 148000,      1],
       [  

                    STANDARIZATION/FEATURE SCALING OF DATA

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [9]:
x_train

array([[ 0.58164944, -0.88670699, -0.98019606],
       [-0.60673761,  1.46173768,  1.02020406],
       [-0.01254409, -0.5677824 , -0.98019606],
       [-0.60673761,  1.89663484, -0.98019606],
       [ 1.37390747, -1.40858358, -0.98019606],
       [ 1.47293972,  0.99784738, -0.98019606],
       [ 0.08648817, -0.79972756,  1.02020406],
       [-0.01254409, -0.24885782,  1.02020406],
       [-0.21060859, -0.5677824 , -0.98019606],
       [-0.21060859, -0.19087153, -0.98019606],
       [-0.30964085, -1.29261101, -0.98019606],
       [-0.30964085, -0.5677824 ,  1.02020406],
       [ 0.38358493,  0.09905991,  1.02020406],
       [ 0.8787462 , -0.59677555, -0.98019606],
       [ 2.06713324, -1.17663843, -0.98019606],
       [ 1.07681071, -0.13288524,  1.02020406],
       [ 0.68068169,  1.78066227, -0.98019606],
       [-0.70576986,  0.56295021, -0.98019606],
       [ 0.77971394,  0.35999821, -0.98019606],
       [ 0.8787462 , -0.53878926, -0.98019606],
       [-1.20093113, -1.58254245,  1.020

                                  IMPORTING OUR MODEL(DECISION TREE)

In [10]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [11]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

                CHECKING ACCURACY_SCORE, CONFUSION_MATRIX

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [13]:
accuracy_score(y_test, y_pred)

0.92

In [14]:
confusion_matrix(y_test, y_pred)

array([[63,  5],
       [ 3, 29]], dtype=int64)

In [15]:
from sklearn import metrics

In [21]:
metrics.mean_absolute_error(y_test, y_pred)

0.08

In [18]:
metrics.mean_squared_error(y_test, y_pred)

0.08

In [ ]:
np.concat

In [19]:
from matplotlib.colors import ListedColormap
x_set, y_set = sc.inverse_transform(x_train), y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:,0].min() - 1, stop = x_set[:,0].max() + 1, step =0.01),
                     np.arange(start = x_set[:,1].min() - 1, stop = x_set[:,1].max() + 1, step =0.01))
plt.contourf(x1,x2, classifier.predict(sc.transform(np.array([x1.ravel(), x2.ravel()]).T)).reshape(x1.shape), 
             alpha = 0.75, cmap = ListedColormap('red','green'))
plt.xlim(x1.min(),x1.max())
plt.ylim(x2.min(),x2.max())
for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j,0], x_set[y_set == j,1], c = ListedColormap(('red','green'))(i), label =j)
plt.title('DecisionTreeClassifier')
plt.xlabel('Age')
plt.ylabel('Est salary')
plt.legend()
plt.show()

MemoryError: Unable to allocate 471. GiB for an array with shape (12801149, 4941) and data type float64